---
title: "Mini-Project 2"
author: "Chujun He, Xuxi Ding "
date: "October 31, 2017"
output: html_document
---


## Loading the data

This project is so interesting and relevant to my life! 

```{r, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```



```{r}
glimpse(house_elections)

```


```{r}
glimpse(candidates)

```


By observing the contribution data frame, we find that most of transaction dates are in 2011 and 2012. Thus, we suppose that the contributions will be most relevant to the election in 2012. 

#can add some information about type of transaction

```{r}

#select certain columns, only need the information we want
#only keep candidates whose election year is 2012
#only examine the Republican party and Democratic party
candidate_2012 <- candidates %>%
  select(cand_id,cand_name,cand_party_affiliation,cand_election_yr,cand_state) %>%
  filter(cand_election_yr == '2012', cand_party_affiliation == 'REP'|cand_party_affiliation == 'DEM')

glimpse(candidate_2012)

#select certain columns, only need the information we want
#only donsider 24E type transaction, which is directly used to support the candidates
#calculate total transaction amount given to a candidate
contributions_24e <- contributions %>%
  filter(transaction_type == "24E") %>%
  select(name,transaction_amt,cand_id,state) %>% 
  group_by(cand_id) %>% 
  summarize(total_trans = sum(transaction_amt))
glimpse(contributions_24e)


#join two data frames 
can_contri_2012 <- candidate_2012 %>% left_join(contributions_24e, by = 'cand_id')
#filter out NA values in total_trans
can_contri_2012 <- can_contri_2012 %>% filter(!is.na(total_trans))

#calculate the total amount of transactions to a party
party_2012 <- can_contri_2012 %>% 
  group_by(cand_party_affiliation) %>% 
  summarize(party_trans = sum(total_trans))

glimpse(can_contri_2012)
glimpse(party_2012)

```

```{r}
#plot the amount of transactions given to support elections of two parties from 2011 to 2012 
ggplot(party_2012, aes(x=cand_party_affiliation, y= party_trans, fill = cand_party_affiliation)) + geom_bar(stat = "identity", width = 0.3) +
  scale_x_discrete(name='Party', label = c('Democratic', 'Republican'))+
  scale_y_continuous(name='Transactions', labels = scales::comma) +
  ggtitle('Total Amount of Received 24E Transactions from 2011 to 2012')

```

```{r}
glimpse(house_elections)

# calculate the amount of Republican and Democratic winners in elections
win_2012 <- house_elections %>% 
  select(candidate_name, party,general_votes,ge_winner)%>%
  filter(party== "R" | party == 'D') %>% 
  group_by(party) %>% 
  filter(ge_winner == 'W') %>% 
  summarize(winner_amt = n())

glimpse(win_2012)
```


```{r}
# function that calculates how much transactions did a party receive in each state
# arrange the data by the amount of transactions
party_state_trans <- function(input_data,input_party){
  input_data %>% 
    filter(cand_party_affiliation == input_party) %>%
    group_by(cand_state) %>% 
    summarize(cand_tran = sum(total_trans)) %>% 
    filter(!is.na(cand_state)) %>%
    arrange(desc(cand_tran))
  }

# Republican received how much transactions in each state
rep_state_tran <- party_state_trans(can_contri_2012,'REP')
#rename the column
rep_state_tran$cand_tran_rep <- rep_state_tran$cand_tran
rep_state_tran$cand_tran <- NULL
glimpse(rep_state_tran)
# Demoncratic received how much transactions in each state
dem_state_tran <- party_state_trans(can_contri_2012,'DEM')
#rename the column
dem_state_tran$cand_tran_dem <- dem_state_tran$cand_tran
dem_state_tran$cand_tran <- NULL
glimpse(dem_state_tran)

two_states_tran <- rep_state_tran %>% full_join(dem_state_tran, by = 'cand_state')

glimpse(two_states_tran)

```



```{r}
glimpse(committees)

```



#Guangzhi: Use this data fram to plot  - From Chujun
```{r}

# select certain columns in committees data frame
comi_can <- committees %>% 
  select(cmte_id, cmte_name, cmte_party_affiliation, cand_id)

glimpse(comi_can)
glimpse(can_contri_2012)

# join two data frams
New_comi_can <- comi_can %>% full_join(can_contri_2012, by = 'cand_id')

# select certain columns and filter out NA values of transactions amounts
# arrange the total trans from most to least 
New_comi_can <- New_comi_can %>% 
  filter(!is.na(total_trans), cmte_party_affiliation == 'REP' | cmte_party_affiliation == 'DEM') %>%   arrange(desc(total_trans))


glimpse(New_comi_can)






```

```{r}

```

```{r}
glimpse(contributions)


```




